# Generated by Django 4.0.5 on 2022-06-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('Course_id', models.AutoField(primary_key=True, serialize=False)),
                ('Cours_Name', models.CharField(max_length=100)),
            ],
        ),
    ]
